import { Correlation } from "./correlation";


export class Movie{
    _id: String // id generated by mongodb
    recId: number // id used by recommandations algorithms
    title: String
    average: number
    ratingNumber: number
    url: String
    genres: [String]
    corr: [Correlation]
}