export class Movie{
    _id: String // id generated by mongodb
    id: Number // id used by recommandations algorithms
    title: String
    average: Number
    ratingNumber: Number
    url: String
    genres: [String]
}